## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
  - 1.4
  - nightly
env:
  - DATADEPS_ALWAYS_ACCEPT=true
cache:
  directories:
    - $HOME/.julia/datadeps
notifications:
  email: false
matrix:
 allow_failures:
 - julia: nightly
branches:
  only:
    - master

before_script:
  - julia -e 'using Pkg; Pkg.activate("notebooks"); include("notebooks/data_dependencies.jl"); @datadep"bouman_edge_cameras_data";'
after_success:
  # push coverage results to Codecov
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'