## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
  - 1.4
  - nightly
env:
  - DATADEPS_ALWAYS_ACCEPT=true
notifications:
  email: false
matrix:
 allow_failures:
 - julia: nightly
branches:
  only:
    - master

before_script:
  - mkdir -p ~/.julia/datadeps
  - pushd ~/.julia/datadeps
  - curl "https://people.csail.mit.edu/klbouman/pw/projects/cornercam/example_videos.zip"
  - unzip example_videos.zip
  - popd
after_success:
  # push coverage results to Codecov
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'